package com.eedu.diagnosis.manager.model.response.question;

import java.io.Serializable;
import java.util.Date;
import java.util.List;




public class ChineseQuestion implements Serializable {
    
    private String id;

   
    private String title;
    private String stem;
    private String ques_option;
    private String ques_analyze;
   
    private List<QuesionOptionModel> quesOptions;
	/**
	 * 解析信息
	 */
    private List<QuestionAnalysisModel> quesAnalyzes;
    
   
    public String getStem() {
		return stem;
	}


	public void setStem(String stem) {
		this.stem = stem;
	}


	


	

	public List<QuesionOptionModel> getQuesOptions() {
		return quesOptions;
	}


	public void QuestionAnalysisModel(List<QuesionOptionModel> quesOptions) {
		this.quesOptions = quesOptions;
	}








	public List<QuestionAnalysisModel> getQuesAnalyzes() {
		return quesAnalyzes;
	}


	public void setQuesAnalyzes(List<QuestionAnalysisModel> quesAnalyzes) {
		this.quesAnalyzes = quesAnalyzes;
	}


	public void setQuesOptions(List<QuesionOptionModel> quesOptions) {
		this.quesOptions = quesOptions;
	}








	private String stem_picture;

   
    private String option_picture;

   
    private String anayze_picture;

    
    private String answer;

   
    private Integer difficult_star;

   
    private String ques_comment;

    private String remark;

   
    private String video_path;

  
    private String audio_listen_path;

   
    private String source;

    
    private String iscompleted;

    
    private String type;

    
    private String isdel;

  
    private String stage_code;

  
    private String subject_name;

    
    private String grade_code;

   
    private String ischecked;

   
    private String check_name;

   
    private Date check_time;

    private String grade_rules;

   
    private Double score;

   
    private String cost_time;

   
    private String estimate_time;

   
    private String make_name;

   
    private Date make_time;

   
    private Integer use_times;

   
    private long create_date;

   
    private String create_by;

   
    private String create_name;

   
    private long update_date;

  
    private String update_by;

   
    private String update_name;

   
    private String application;

   
    private String audio_analyze_path;

    
    private String productions;

    
    private String production_code;

   
    private String enlarge_id;

   
    private String knowledges;

   
    private String fit_code;

   
    private static final long serialVersionUID = 1L;

  
    public String getId() {
        return id;
    }

   
    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

   
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.stem_picture
     *
     * @return the value of math_question.stem_picture
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
   
 

   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.answer
     *
     * @return the value of math_question.answer
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column math_question.answer
     *
     * @param answer the value for math_question.answer
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.ques_comment
     *
     * @return the value of math_question.ques_comment
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.remark
     *
     * @return the value of math_question.remark
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column math_question.remark
     *
     * @param remark the value for math_question.remark
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.source
     *
     * @return the value of math_question.source
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column math_question.source
     *
     * @param source the value for math_question.source
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.iscompleted
     *
     * @return the value of math_question.iscompleted
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public String getIscompleted() {
        return iscompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column math_question.iscompleted
     *
     * @param iscompleted the value for math_question.iscompleted
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public void setIscompleted(String iscompleted) {
        this.iscompleted = iscompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.type
     *
     * @return the value of math_question.type
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column math_question.type
     *
     * @param type the value for math_question.type
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.isdel
     *
     * @return the value of math_question.isdel
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public String getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column math_question.isdel
     *
     * @param isdel the value for math_question.isdel
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public void setIsdel(String isdel) {
        this.isdel = isdel;
    }

   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.grade_code
     *
     * @return the value of math_question.grade_code
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.ischecked
     *
     * @return the value of math_question.ischecked
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public String getIschecked() {
        return ischecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column math_question.ischecked
     *
     * @param ischecked the value for math_question.ischecked
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public void setIschecked(String ischecked) {
        this.ischecked = ischecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.score
     *
     * @return the value of math_question.score
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column math_question.score
     *
     * @param score the value for math_question.score
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public void setScore(Double score) {
        this.score = score;
    }

 

   

   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.application
     *
     * @return the value of math_question.application
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public String getApplication() {
        return application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column math_question.application
     *
     * @param application the value for math_question.application
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public void setApplication(String application) {
        this.application = application;
    }

   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column math_question.productions
     *
     * @return the value of math_question.productions
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public String getProductions() {
        return productions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column math_question.productions
     *
     * @param productions the value for math_question.productions
     *
     * @mbggenerated Thu Apr 28 10:58:56 CST 2016
     */
    public void setProductions(String productions) {
        this.productions = productions;
    }


	public String getQues_option() {
		return ques_option;
	}


	public void setQues_option(String ques_option) {
		this.ques_option = ques_option;
	}


	public String getQues_analyze() {
		return ques_analyze;
	}


	public void setQues_analyze(String ques_analyze) {
		this.ques_analyze = ques_analyze;
	}


	public String getStem_picture() {
		return stem_picture;
	}


	public void setStem_picture(String stem_picture) {
		this.stem_picture = stem_picture;
	}


	public String getOption_picture() {
		return option_picture;
	}


	public void setOption_picture(String option_picture) {
		this.option_picture = option_picture;
	}


	public String getAnayze_picture() {
		return anayze_picture;
	}


	public void setAnayze_picture(String anayze_picture) {
		this.anayze_picture = anayze_picture;
	}


	public Integer getDifficult_star() {
		return difficult_star;
	}


	public void setDifficult_star(Integer difficult_star) {
		this.difficult_star = difficult_star;
	}


	public String getQues_comment() {
		return ques_comment;
	}


	public void setQues_comment(String ques_comment) {
		this.ques_comment = ques_comment;
	}


	public String getVideo_path() {
		return video_path;
	}


	public void setVideo_path(String video_path) {
		this.video_path = video_path;
	}


	public String getAudio_listen_path() {
		return audio_listen_path;
	}


	public void setAudio_listen_path(String audio_listen_path) {
		this.audio_listen_path = audio_listen_path;
	}


	public String getStage_code() {
		return stage_code;
	}


	public void setStage_code(String stage_code) {
		this.stage_code = stage_code;
	}


	public String getSubject_name() {
		return subject_name;
	}


	public void setSubject_name(String subject_name) {
		this.subject_name = subject_name;
	}


	public String getGrade_code() {
		return grade_code;
	}


	public void setGrade_code(String grade_code) {
		this.grade_code = grade_code;
	}


	public String getCheck_name() {
		return check_name;
	}


	public void setCheck_name(String check_name) {
		this.check_name = check_name;
	}


	public Date getCheck_time() {
		return check_time;
	}


	public void setCheck_time(Date check_time) {
		this.check_time = check_time;
	}


	public String getGrade_rules() {
		return grade_rules;
	}


	public void setGrade_rules(String grade_rules) {
		this.grade_rules = grade_rules;
	}


	public String getCost_time() {
		return cost_time;
	}


	public void setCost_time(String cost_time) {
		this.cost_time = cost_time;
	}


	public String getEstimate_time() {
		return estimate_time;
	}


	public void setEstimate_time(String estimate_time) {
		this.estimate_time = estimate_time;
	}


	public String getMake_name() {
		return make_name;
	}


	public void setMake_name(String make_name) {
		this.make_name = make_name;
	}


	public Date getMake_time() {
		return make_time;
	}


	public void setMake_time(Date make_time) {
		this.make_time = make_time;
	}


	public Integer getUse_times() {
		return use_times;
	}


	public void setUse_times(Integer use_times) {
		this.use_times = use_times;
	}


	
	public String getCreate_by() {
		return create_by;
	}


	public void setCreate_by(String create_by) {
		this.create_by = create_by;
	}


	public String getCreate_name() {
		return create_name;
	}


	public void setCreate_name(String create_name) {
		this.create_name = create_name;
	}


	


	public String getUpdate_by() {
		return update_by;
	}


	public void setUpdate_by(String update_by) {
		this.update_by = update_by;
	}


	public String getUpdate_name() {
		return update_name;
	}


	public void setUpdate_name(String update_name) {
		this.update_name = update_name;
	}


	public String getAudio_analyze_path() {
		return audio_analyze_path;
	}


	public void setAudio_analyze_path(String audio_analyze_path) {
		this.audio_analyze_path = audio_analyze_path;
	}


	public String getProduction_code() {
		return production_code;
	}


	public void setProduction_code(String production_code) {
		this.production_code = production_code;
	}


	public String getEnlarge_id() {
		return enlarge_id;
	}


	public void setEnlarge_id(String enlarge_id) {
		this.enlarge_id = enlarge_id;
	}


	public String getKnowledges() {
		return knowledges;
	}


	public void setKnowledges(String knowledges) {
		this.knowledges = knowledges;
	}


	public String getFit_code() {
		return fit_code;
	}


	public void setFit_code(String fit_code) {
		this.fit_code = fit_code;
	}


	public static long getSerialversionuid() {
		return serialVersionUID;
	}


	public long getCreate_date() {
		return create_date;
	}


	public void setCreate_date(long create_date) {
		this.create_date = create_date;
	}


	public long getUpdate_date() {
		return update_date;
	}


	public void setUpdate_date(long update_date) {
		this.update_date = update_date;
	}

   

  
   
  
}